<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>omniplanner_ros</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="aaronray@mit.edu">aaron</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>tf2_ros</depend>
  <depend>tf_transformations</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>builtin_interfaces</depend>

  <depend>hydra_msgs</depend>
  <depend>omniplanner_msgs</depend>
  <depend>robot_executor_msgs</depend>
  <depend>ros_system_monitor_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
